# Generated by Django 5.2.5 on 2025-08-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do serviço (ex: Montagem de PC).', max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do serviço em R$.', max_digits=10)),
                ('duracao_estimada', models.CharField(blank=True, help_text='Duração estimada do serviço (ex: 2-3 horas).', max_length=100)),
                ('descricao', models.TextField(help_text='Descrição detalhada do que está incluído no serviço.')),
                ('disponivel', models.BooleanField(default=True, help_text='Indica se o serviço está disponível para contratação.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data em que o serviço foi cadastrado.')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização do serviço.')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
