# Generated by Django 5.2.5 on 2025-08-14 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api_Categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto (ex: Intel Core i7-13700K).', max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto em R$.', max_digits=10)),
                ('descricao', models.TextField(help_text='Descrição detalhada do produto.')),
                ('url_imagem', models.URLField(blank=True, help_text='URL da imagem principal do produto.', null=True)),
                ('em_estoque', models.BooleanField(default=True, help_text='Indica se o produto está disponível em estoque.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data em que o produto foi cadastrado.')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização do produto.')),
                ('categoria', models.ForeignKey(help_text='Categoria à qual o produto pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='Api_Categoria.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
