# Generated by Django 5.2.5 on 2025-08-15 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=200)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificacoes', to='Api_Produto.produto')),
            ],
            options={
                'verbose_name': 'Especificação Técnica',
                'verbose_name_plural': 'Especificações Técnicas',
            },
        ),
    ]
